#include <nds.h>
#include <stdio.h>
#include <string.h>
#include <gl2d.h>
// #include <combined.h>
#include <crab.h>

// static enum { CONTINUOUS, SINGLE } TouchType = CONTINUOUS;

glImage Crab[1];

//---------------------------------------------------------------------------------
int main(void) {
//---------------------------------------------------------------------------------
	// int min_x  = 4096 , min_y  = 4096, max_x  = 0, max_y   = 0;
	// int min_px = 4096 , min_py = 4096, max_px = 0 , max_py = 0;
	// touchPosition touch;

	// put the main screen on the bottom lcd
	lcdMainOnBottom();


	// Sprite initialisation
	// oamInit(&oamMain, SpriteMapping_1D_32, false);
  videoSetMode( MODE_5_3D );

	// enable vram and map it to the right places
	// vramSetPrimaryBanks(
	// 	VRAM_A_MAIN_BG,     //map A to background memory
	// 	VRAM_B_MAIN_SPRITE, //map B to sprite memory
	// 	VRAM_C_LCD,         //not using C
	// 	VRAM_D_LCD          //not using D
	// );

  // draw a white background
  // int bg = bgInit(3, BgType_Text8bpp, BgSize_T_256x256, 0,0);
  consoleDemoInit();

  int keys = 0;

  // int CrabTextureID =
	// 	glLoadTileSet( Crab,			// pointer to glImage array
  //     48,				// sprite width
  //     48,				// sprite height
  //     48,				// bitmap image width
  //     48,				// bitmap image height
  //     GL_RGB256,		// texture type for glTexImage2D() in videoGL.h
  //     TEXTURE_SIZE_64,	// sizeX for glTexImage2D() in videoGL.h
  //     TEXTURE_SIZE_64,	// sizeY for glTexImage2D() in videoGL.h
  //     GL_TEXTURE_WRAP_S|GL_TEXTURE_WRAP_T|TEXGEN_OFF|GL_TEXTURE_COLOR0_TRANSPARENT,
  //     16,					// Length of the palette to use (16 colors)
  //     (u16*)crabPal,	// Load our 256 color Shuttle palette
  //     (u8*)crabBitmap  // image data generated by GRIT
  //   );

	glScreen2D();

  while(pmMainLoop() && !(keys & KEY_B))
  {

		glBegin2D();
    // glSprite(30, 30,  GL_FLIP_NONE,           &Crab[0]);

    glTriangleFilled( 20, 100,
						  200, 30,
						  60, 40,
						  RGB15(31,0,31)
						);


    glEnd2D();

    glFlush(0);

    swiWaitForVBlank();
    scanKeys();
    keys = keysHeld();
  }


	return 0;
}
